[tools]
"aqua:atuinsh/atuin" = "latest"
bat = "latest"
delta = "latest"
direnv = "latest"
dust = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
helix = "latest"
jj = "latest"
just = "latest"
lefthook = "latest"
pre-commit = "latest"
ripgrep = "latest"
starship = "latest"
"aqua:tealdeer-rs/tealdeer" = "latest"
usage = "latest"
uv = "latest"
viddy = "latest"
yazi = "latest"
zoxide = "latest"

[env]
AZCOPY_AUTO_LOGIN_TYPE = "AZCLI"
AZURE_CORE_COLLECT_TELEMETRY = 0
JUPYTER_PLATFORM_DIRS = 1

[settings]
# https://github.com/jdx/mise/discussions/4345
idiomatic_version_file_enable_tools = []
